# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geocoding.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'geocoding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgeocoding.proto\x12\tgeocoding\"\x0e\n\x0cHelloRequest\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2G\n\tGeocoding\x12:\n\x05Hello\x12\x17.geocoding.HelloRequest\x1a\x18.geocoding.HelloResponseB\x11Z\x0fgeocoding/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geocoding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017geocoding/proto'
  _globals['_HELLOREQUEST']._serialized_start=30
  _globals['_HELLOREQUEST']._serialized_end=44
  _globals['_HELLORESPONSE']._serialized_start=46
  _globals['_HELLORESPONSE']._serialized_end=78
  _globals['_GEOCODING']._serialized_start=80
  _globals['_GEOCODING']._serialized_end=151
# @@protoc_insertion_point(module_scope)
