// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/geocoding.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Geocoding_Geocode_FullMethodName        = "/geocoding.Geocoding/Geocode"
	Geocoding_ReverseGeocode_FullMethodName = "/geocoding.Geocoding/ReverseGeocode"
)

// GeocodingClient is the client API for Geocoding service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeocodingClient interface {
	Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error)
	ReverseGeocode(ctx context.Context, in *ReverseGeocodeRequest, opts ...grpc.CallOption) (*ReverseGeocodeResponse, error)
}

type geocodingClient struct {
	cc grpc.ClientConnInterface
}

func NewGeocodingClient(cc grpc.ClientConnInterface) GeocodingClient {
	return &geocodingClient{cc}
}

func (c *geocodingClient) Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeocodeResponse)
	err := c.cc.Invoke(ctx, Geocoding_Geocode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocodingClient) ReverseGeocode(ctx context.Context, in *ReverseGeocodeRequest, opts ...grpc.CallOption) (*ReverseGeocodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseGeocodeResponse)
	err := c.cc.Invoke(ctx, Geocoding_ReverseGeocode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeocodingServer is the server API for Geocoding service.
// All implementations must embed UnimplementedGeocodingServer
// for forward compatibility.
type GeocodingServer interface {
	Geocode(context.Context, *GeocodeRequest) (*GeocodeResponse, error)
	ReverseGeocode(context.Context, *ReverseGeocodeRequest) (*ReverseGeocodeResponse, error)
	mustEmbedUnimplementedGeocodingServer()
}

// UnimplementedGeocodingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeocodingServer struct{}

func (UnimplementedGeocodingServer) Geocode(context.Context, *GeocodeRequest) (*GeocodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Geocode not implemented")
}
func (UnimplementedGeocodingServer) ReverseGeocode(context.Context, *ReverseGeocodeRequest) (*ReverseGeocodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseGeocode not implemented")
}
func (UnimplementedGeocodingServer) mustEmbedUnimplementedGeocodingServer() {}
func (UnimplementedGeocodingServer) testEmbeddedByValue()                   {}

// UnsafeGeocodingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeocodingServer will
// result in compilation errors.
type UnsafeGeocodingServer interface {
	mustEmbedUnimplementedGeocodingServer()
}

func RegisterGeocodingServer(s grpc.ServiceRegistrar, srv GeocodingServer) {
	// If the following call panics, it indicates UnimplementedGeocodingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Geocoding_ServiceDesc, srv)
}

func _Geocoding_Geocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocodingServer).Geocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocoding_Geocode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocodingServer).Geocode(ctx, req.(*GeocodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocoding_ReverseGeocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseGeocodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocodingServer).ReverseGeocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocoding_ReverseGeocode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocodingServer).ReverseGeocode(ctx, req.(*ReverseGeocodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Geocoding_ServiceDesc is the grpc.ServiceDesc for Geocoding service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Geocoding_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geocoding.Geocoding",
	HandlerType: (*GeocodingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Geocode",
			Handler:    _Geocoding_Geocode_Handler,
		},
		{
			MethodName: "ReverseGeocode",
			Handler:    _Geocoding_ReverseGeocode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/geocoding.proto",
}
